name: reviewdog

on: [pull_request]

jobs:
  shellcheck:
    name: Runner / ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2.3.3

      - name: Run | shellcheck-github-pr-check
        uses: reviewdog/action-shellcheck@v1.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run | shellcheck-github-check
        uses: reviewdog/action-shellcheck@v1.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: warning
          filter_mode: file
          pattern: "*.sh"
          path: "./src"
          shellcheck_flags: "--external-sources --severity=style"

      - name: Run | shellcheck-github-pr-review
        uses: reviewdog/action-shellcheck@v1.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          pattern: "*.sh"
          path: "./src"
